/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class cgdActor extends foundry.documents.Actor {
  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    const flags = actorData.flags.coriolistgd || {};
    this.system.maxPush ??= {};
    this.system.attributesBonus ??= {};
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  _replaceImgIfDefault(img) {
    return this.img == "icons/svg/mystery-man.svg" ? img : this.img;
  }
  _replaceTokenImgIfDefault(img) {
    return this.prototypeToken.texture.src == "icons/svg/mystery-man.svg" ? img : this.prototypeToken.texture.src;
  }
  _replaceActorLink(data, defaultValue) {
    return data.prototypeToken?.actorLink ?? defaultValue;
  }

  async _preCreate(data, options, user) {
    const allowed = await super._preCreate(data, options, user)
    if (allowed === false) return false;

    switch (data.type) {
      case "explorer":
        this.updateSource({
          img: this._replaceImgIfDefault("systems/coriolis-tgd/assets/icons/astronaut-helmet.svg"),
          prototypeToken: {
            actorLink: true,
            disposition: 0,
            sight: {
              enabled: true
            },
            texture: {
              src: this._replaceTokenImgIfDefault("systems/coriolis-tgd/assets/icons/tokens/astronaut-helmet.webp")
            }
          }
        });
        break;
      case "npc":
        this.updateSource({
          img: this._replaceImgIfDefault("systems/coriolis-tgd/assets/icons/npc.svg"),
          prototypeToken: {
            actorLink: this._replaceActorLink(data, false),
            disposition: 0,
            sight: {
              enabled: true
            },
            texture: {
              src: this._replaceTokenImgIfDefault("systems/coriolis-tgd/assets/icons/tokens/npc.webp")
            }
          }
        });
        break;
      case "creature":
        this.updateSource({
          img: this._replaceImgIfDefault("systems/coriolis-tgd/assets/icons/creature.svg"),
          prototypeToken: {
            actorLink: false,
            disposition: 0,
            sight: {
              enabled: true
            },
            texture: {
              src: this._replaceTokenImgIfDefault("systems/coriolis-tgd/assets/icons/tokens/creature.webp")
            }
          }
        });
        break;
      case "bird":
        this.updateSource({
          img: this._replaceImgIfDefault("systems/coriolis-tgd/assets/icons/egyptian-bird.svg"),
          ownership: { default: CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER },
          prototypeToken: {
            actorLink: true,
            disposition: 0,
            sight: {
              enabled: true
            },
            texture: {
              src: this._replaceTokenImgIfDefault("systems/coriolis-tgd/assets/icons/tokens/egyptian-bird.webp"),
            }
          }
        });
        break;
      case "crew":
        this.updateSource({
          img: this._replaceImgIfDefault("systems/coriolis-tgd/assets/icons/three-friends.svg"),
          ownership: { default: CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER },
          prototypeToken: {
            actorLink: true,
            disposition: 0,
            sight: {
              enabled: true
            },
            texture: {
              src: this._replaceTokenImgIfDefault("systems/coriolis-tgd/assets/icons/tokens/three-friends.webp"),
            }
          }
        });
        break;
      case "kite":
        this.updateSource({
          img: this._replaceImgIfDefault("systems/coriolis-tgd/assets/icons/kite.svg"),
          ownership: { default: CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER },
          prototypeToken: {
            actorLink: true,
            disposition: 0,
            sight: {
              enabled: true
            },
            texture: {
              src: this._replaceTokenImgIfDefault("systems/coriolis-tgd/assets/icons/tokens/kite.webp"),
            }
          }
        });
        break;
      case "rover":
        this.updateSource({
          img: this._replaceImgIfDefault("systems/coriolis-tgd/assets/icons/apc.svg"),
          ownership: { default: CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER },
          prototypeToken: {
            actorLink: true,
            disposition: 0,
            sight: {
              enabled: true
            },
            texture: {
              src: this._replaceTokenImgIfDefault("systems/coriolis-tgd/assets/icons/tokens/apc.webp"),
            }
          }
        });
        break;
      case "shuttle":
        this.updateSource({
          img: this._replaceImgIfDefault("systems/coriolis-tgd/assets/icons/spaceship.svg"),
          ownership: { default: CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER },
          prototypeToken: {
            actorLink: true,
            disposition: 0,
            sight: {
              enabled: true
            },
            texture: {
              src: this._replaceTokenImgIfDefault("systems/coriolis-tgd/assets/icons/tokens/spaceship.webp"),
            }
          }
        });
        break;
      default:
        break;
    }
  }


  /**
   * Get all ActiveEffects that may apply to this Actor. This will also return all the transferred ActiveEffects on any
   * of the Actor's owned Items.
   * @yields {ActiveEffect}
   * @returns {Generator<ActiveEffect, void, void>}
   */
  *allApplicableEffects() {
    for (const effect of this.effects) {
      yield effect;
    }
    for (const item of this.items) {
      for (const effect of item.effects) {
        if (!effect.transfer) continue;

        const updatedEffect = foundry.utils.deepClone(effect);

        if (!updatedEffect.system.changes.length && updatedEffect.statuses.size) {
          for (const status of updatedEffect.statuses) {
            const statusConfig = CONFIG.statusEffects.find(it => it.id == status);
            if (!statusConfig)
              continue;

            updatedEffect.system.changes.push(...statusConfig.changes.map(change => {
              const c = foundry.utils.deepClone(change);
              c.effect = effect;
              c.priority = c.priority ?? (c.mode);
              c.phase = "initial";
              return c;
            }))
          }
        }
        yield updatedEffect;
      }
    }
  }

  getSupplyItem() {
    const supplyItem = this.items.filter(it => it.flags["coriolis-tgd"]?.isSupply)[0];
    return supplyItem;
  }

  get isBroken() {
    return (this.system.derivedAttributes?.health?.value ?? 1) == 0 ||
      (this.system.derivedAttributes?.hope?.value ?? 1) == 0 ||
      (this.system.derivedAttributes?.heart?.value ?? 1) == 0 ||
      (this.system.health?.value ?? 1) == 0;
  }
}
